"""Add property upgrade

Revision ID: 80b95707e2c2
Revises: e2f771bdf4d1
Create Date: 2024-06-20 21:45:10.168462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80b95707e2c2'
down_revision = 'e2f771bdf4d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('date_range', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=False))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('rating',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_column('image')
        batch_op.drop_column('details')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('date_range', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=False))
        batch_op.alter_column('price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_constraint('property_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('sold')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('sold', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('property_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.alter_column('price',
               existing_type=sa.String(length=50),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('image_url')
        batch_op.drop_column('rating')
        batch_op.drop_column('date_range')
        batch_op.drop_column('location')
        batch_op.drop_column('name')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('image', mysql.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('rating',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('image_url')
        batch_op.drop_column('date_range')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
